name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup_job:
    uses: ./.github/workflows/setup-python-poetry.yml

  test:
    needs: setup_job
    runs-on: ubuntu-latest
    steps:
      - run: poetry run task test

  lint:
    needs: setup_job
    runs-on: ubuntu-latest
    steps:
      - run: poetry run task lint

  format:
    needs: setup_job
    runs-on: ubuntu-latest
    steps:
      - run: poetry run task format
